// import settings
:site_resource: src/site/resources
include::{site_resource}/proj-common.adoc[opts=optional]

= {proj_module}

link:{proj_vcsid_url}/-/releases[image:{cmmn_badge_url}/release-latest-blue?logo=gitlab{cmmn_img_style}[Latest Version]]
link:LICENSE[image:{cmmn_badge_url}/license-license-brightgreen?logo=gitlab{cmmn_img_style}[Software License]]
link:{proj_mvnid_url}[image:{cmmn_badge_maven_url}/v/{proj_gav}?logo=apache-maven{cmmn_img_style}[Maven]]

{proj_description}
See link:{proj_user_url}[Homepage].

== Project Status

See link:readme-status.adoc[Project Status].

link:{cmmn_sonar_dash_url}?id={proj_sonarid}[image:{cmmn_sonar_badge_url}/sonarcloud-black.svg[SonarCloud]]

== Installation

Install link:https://maven.apache.org/install.html[Maven].

== Usage

To use, set in your `pom.xml`:

.pom.xml
[source,html,subs="attributes"]
----
&lt;parent&gt;
  &lt;groupId&gt;{proj_group}&lt;/groupId&gt;
  &lt;artifactId&gt;{proj_module}&lt;/artifactId&gt;
  &lt;version&gt;{proj_version}&lt;/version&gt;
&lt;/parent&gt;
----

== Author

- {proj_author_url}

== License

This project is released under version 2.0 of the link:{proj_vcsid_url}/-/blob/master/LICENSE[Apache License].
Please see the link:{proj_vcsid_url}/-/blob/master/LICENSE[license file] for more information.

''''
~{proj_cright}~
