// import settings
:site_resource: src/site/resources
include::{site_resource}/proj-common.adoc[opts=optional]

= {proj_module}

{cmmn_backlink}

== Quality Information

{cmmn_sonar_dash_url}?id={proj_sonarid}[image:{cmmn_sonar_api_url}/project_badges/quality_gate?project={proj_sonarid}[title="Quality Gate"]]

// link:{cmmn_coverity_dash_url}/{proj_module}[image:{cmmn_badge_coverity_url}/{proj_id_coverity}?{cmmn_coverity_ref}{cmmn_img_style}[title="Coverity Scan Status"]]
link:{cmmn_codacy_dash_url}/{proj_vcsid}[image:{cmmn_badge_codacy_url}/{proj_id_codacy}?{cmmn_codacy_ref}{cmmn_img_style}[title="Codacy Scan Status"]]
// link:{cmmn_badge_openssf_url}/{proj_id_openssf}[image:{cmmn_openssf_dash_url}/{proj_id_openssf}/badge[title="CII Best Practices"]]

== Build Information
:brnch_1: develop
:brnch_2: master
{proj_pipe_url}{brnch_1}[
image:{cmmn_badge_gitlab_status_url}/{proj_vcsid}?branch={brnch_1}&label={brnch_1}{cmmn_img_gitlab_style}[title="Pipeline status on {brnch_1} branch"]]
{proj_pipe_url}{brnch_2}[
image:{cmmn_badge_gitlab_status_url}/{proj_vcsid}?branch={brnch_2}&label={brnch_2}{cmmn_img_gitlab_style}[title="Pipeline status on {brnch_2} branch"]]
{proj_vcsid_url}/-/releases[image:{proj_vcsid_url}/-/badges/release.svg[title="Latest Release"]]

== Test Information

*_No tests in this project!_*
////
{cmmn_sonar_dash_url}?id={proj_sonarid}[image:{cmmn_badge_sonar_url}/test_success_density/{proj_sonarid}?{cmmn_sonar_ref}{cmmn_img_style}[title="Test Status"]]
{cmmn_sonar_dash_url}?id={proj_sonarid}[image:{cmmn_badge_sonar_url}/tests/{proj_sonarid}?{cmmn_sonar_ref}{cmmn_img_style}[title="Test Count"]]
{cmmn_sonar_dash_url}?id={proj_sonarid}[image:{cmmn_badge_sonar_url}/coverage/{proj_sonarid}?{cmmn_sonar_ref}{cmmn_img_style}[title="Coverage by Gitlab"]]
{cmmn_sonar_dash_url}?id={proj_sonarid}[image:{cmmn_sonar_api_url}/project_badges/measure?project={proj_sonarid}&metric=coverage[title="Coverage by Sonarqube"]]
{cmmn_coveralls_dash_url}/{proj_vcsid}?branch={brnch_1}[image:{cmmn_badge_coveralls_url}/{proj_vcsid}/badge.svg?branch={brnch_1}[title="{brnch_1} Coveralls Status"]]
{cmmn_coveralls_dash_url}/{proj_vcsid}?branch={brnch_2}[image:{cmmn_badge_coveralls_url}/{proj_vcsid}/badge.svg?branch={brnch_2}[title="{brnch_2} Coveralls Status"]]
////


''''
{cmmn_backlink}

~{proj_cright}~
